version: '3.8'

services:
  db:
    image: postgres
    container_name: videotecha_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videotecha
    ports:
      - '5432:5432'
