spring:
  flyway:
    locations: classpath:db
    baseline-on-migrate: true
    check-location: true
    enabled: true
    sql-migration-prefix: v
    sql-migration-suffix: .sql
  datasource:
    url: jdbc:postgresql://localhost:5432/videotecha
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: yes
    hibernate:
      ddl-auto: none
    show-sql: yes

