rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  flyway:
    locations: classpath:db
    baseline-on-migrate: true
    check-location: true
    enabled: true
    sql-migration-prefix: v
    sql-migration-suffix: .sql
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videotecha}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: yes
    hibernate:
      ddl-auto: none
    show-sql: yes
  mail:
    host: smtp.gmail.com
    port: 587
    username: stefanpraksa7@gmail.com
    password: fmlegaqzkawuhnsx
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
springdoc:
  api-docs:
    path: /videotecha-openapi
omdbAPI:
  search-by-title: https://www.omdbapi.com/?type=movie&apikey=d8279094&s=
  search-by-imdbID: http://www.omdbapi.com/?apikey=d8279094&i=
